### ISSUE TITLE
can't I use arrow keys?

### ISSUE THREAD

**Issue by wb670** [18alantom/fex#5]
starting with the command fex can be controlled using the arrow keys
but starting with hot key "^f" i can't use arrow keys only can use J,K
by macOS

**Comment by 18alantom** [comment]
Should be fixed in the latest release: https://github.com/18alantom/fex/releases/tag/v0.1.1

Appears to be that the bytes representing arrow keys are different when running as a zsh widget. The middle value changes from `91` to `79`. So for instance down key becomes `{27, 79, 66}` instead of `{27, 91, 66}`.
